server:
  port: 8085

spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud.bus.enabled: false
  cloud.config.server.git:
    username: pauljgl2008
    password: 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
    uri: https://github.com/pauljgl2008/demo-pjgl-enviroments-secrets
    default-label: main
    timeout: 5
    clone-on-start: true
    force-pull: true
    refresh-rate: 0
  #cloud:
    #stream:
      #rabbit:
        #enabled: false
  key: "MYSECRETKEY"

management:
  endpoints:
    web:
      exposure:
        include: "*"