name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Git Semantic Version
      uses: paulhatch/semantic-version@v5.3.0
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        version_format: "${major}.${minor}.${patch}"
      id: version

    - name: Docker login
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
            pguevarl/config-server:${{ steps.version.outputs.version }}
            pguevarl/config-server:latest
        platforms: linux/amd64,linux/arm64,linux/arm/v7