name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Git Semantic Version
      uses: paulhatch/semantic-version@v5.3.0
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        version_format: "${major}.${minor}.${patch}"
      id: version

    - name: Docker login
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      uses: docker/build-push-action@v3
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      with:
        push: false  # Set to true if you want to push the image
        tags: ${{ steps.version.outputs.version }}
        build_args: $NEW_VERSION
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        cache_from: type=registry,ref=https://hub.docker.com/repository/docker/pguevarl/config-server:build-cache  # Optional: Use build cache

#    - name: Build Docker Image
#      env:
#        NEW_VERSION: ${{ steps.version.outputs.version }}
#      run: |
#        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t pguevarl/config-server:$NEW_VERSION .
#        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t pguevarl/config-server:latest .
    
    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push pguevarl/config-server:$NEW_VERSION
        docker push pguevarl/config-server:latest
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
